nats-io/jsm.go

api/consumers.go, api/jetstream.go, api/stream_templates.go, api/streams.go, consumers.go, go.mod, go.sum, jsm.go, jsm_test.go, streams.go, templates.go
=> implement new json based api

api/server/advisory/client_connect.go, api/server/advisory/client_disconnect.go
On reading the old output, I saw `Language: go 1.11.0` which I read as meaning "version 1.11.0 of Golang".  This is not what the version field is supposed to mean: it's a version of the library.
This is attempt 1 at rephrasing the Extended Text output format to categorise a little differently.  I suspect that this particular wording won't be accepted and that's fine — this highlights the two bits of code which should change and folks can debate the better phrasing.
With this particular incarnation of a fix, I now see:
Library: version=1.11.0 language=go
=> Use more precise terminology re library versions

go.mod, go.sum, stream_pager.go, stream_pager_test.go
This uses the new next message structure and the 404 behaviour
to detect end of stream without relying on any timeouts
=> speed up stream pager by using new next msg request

manager.go
This should fix this:
```
$ nats con report bigtest
panic: runtime error: index out of range [1250] with length 16
goroutine 1 [running]:
github.com/nats-io/jsm%2ego.(*Manager).Consumers.func2(0x0, 0x4e2, 0x16665c0)
/Users/rip/go/pkg/mod/github.com/nats-io/jsm.go@v0.0.24/manager.go:363 +0x87
sort.medianOfThree_func(0xc000315848, 0xc000368ae0, 0x0, 0x4e2, 0x9c4)
/usr/local/go/src/sort/zfuncversion.go:53 +0x3e
sort.doPivot_func(0xc000315848, 0xc000368ae0, 0x0, 0x2710, 0x2710, 0x5481800)
/usr/local/go/src/sort/zfuncversion.go:76 +0x4fc
sort.quickSort_func(0xc000315848, 0xc000368ae0, 0x0, 0x2710, 0x1c)
/usr/local/go/src/sort/zfuncversion.go:143 +0x97
sort.Slice(0x16167a0, 0xc0000a34d0, 0xc000315848)
/usr/local/go/src/sort/slice.go:20 +0xe8 …
```
=> Fix call to sort.Slice() that uses wrong slice

api/schemas_generated.go, schema_source/jetstream/api/v1/definitions.json, streams.go, streams_test.go
=> clearer API around sealing streams

stream_query.go, stream_query_test.go
Performance of querying each consumer is just too slow
=> do not involve consumers in idle streams

natscontext/context.go
Previously if --nsc was specified on the CLI
it would add the nsc lookup url but ALSO a server
url based on DefaultURL. And then that would win
over whatever nsc set.
Now that default is only set when no nsc or url is
given
=> improve handling of context urls

consumers.go, streams.go
These 2 methods were written before we had error codes so we had
no choice but to just handle any error and try to create it.
Now we can tighten this up a bit and only specifically handle the
one error for resource not found, the rest are returned as the
original error.  This should avoid some weird conditions in code
that tries to recover from missing streams
=> Ensure LoadOrNEw does not try to remake existing

api/gen.go, api/jetstream/advisory/nak.go, api/schemas_generated.go, schema_source/jetstream/advisory/v1/nak.json, schemas/jetstream/advisory/v1/nak.json
This is a follow up to:
+ Issue: https://github.com/nats-io/nats-server/issues/3072
+ Implementation PR: https://github.com/nats-io/nats-server/pull/3074
+ Documentation PR: https://github.com/nats-io/nats.docs/pull/416
I put the domain only in the ExtendedTemplate as it might be too long for the compact version. If you wish, I will put it also in the CompactTemplate.
=> Add schema for JSConsumerDeliveryNakAdvisory

natscontext/context.go
Use output since stderr is combined. The `err` value only states `exit status 1` for the process exit code.
=> Use stderr for nsc invoke failed

natscontext/context.go, natscontext/context_test.go, natscontext/testdata/nats/context/multi_creds.json
Ran into this debugging/interacting with users, currently you can save multiple types of credentials in a context, which can lead to some pretty confusing behavior when trying to connect.
Still up in the air whether this should live here or in `nats context
validate`, and open to opinions.
=> [fix] Prevent saving when multiple credentials exist

natscontext/context.go, natscontext/context_test.go, natscontext/testdata/nats/context/user_pass_token_creds.json
NATS CLI currently uses the `--username` flag to create both the username and token fields in the nats context, leading to a validation error. In order to not break backward compatibility with NATS cli, I've opted to remove `token` from the list of validations, and included a regression test.
=> remove validation where username, password and token are set

schema_source/jetstream/api/v1/definitions.json, schemas/jetstream/api/v1/stream_configuration.json, schemas/jetstream/api/v1/stream_create_request.json, schemas/jetstream/api/v1/stream_create_response.json, schemas/jetstream/api/v1/stream_info_response.json, schemas/jetstream/api/v1/stream_list_response.json, schemas/jetstream/api/v1/stream_restore_request.json, schemas/jetstream/api/v1/stream_snapshot_response.json, schemas/jetstream/api/v1/stream_template_configuration.json, schemas/jetstream/api/v1/stream_template_create_request.json, schemas/jetstream/api/v1/stream_template_create_response.json, schemas/jetstream/api/v1/stream_template_info_response.json, schemas/jetstream/api/v1/stream_update_request.json, schemas/jetstream/api/v1/stream_update_response.json
We will support basic per-message compression on memory stores too, so this comment is no longer true.
=> Update compression comment

natscontext/context.go
NATS CLI cannot request WebSocket servers behind a proxy - the `proxyPath` option is missing in the config. Since another parameter would be overkill I introduce a change in the `NATSOptions` function that simply takes the path from the `serverURL` and saves it as `proxyPath` in the options object.
A related issue in CLI repo: https://github.com/nats-io/natscli/issues/639.
=> feat: use path from serverURL as proxyPath

natscontext/context.go
The mentioned PR treats the nats url as a single string and then parse it as if it is one url.  The reality is multiple urls are supported there so this is simply not going to work
Further conceptually it tries to take the proxy path from the url - but as this supports multiple urls this just doesnt make sense
The right fix is for nats.go to get the proxypath behaviour per connection url rather than try to fix this here
=> Revert https://github.com/nats-io/jsm.go/pull/487

consumers.go
The `FilterStreamBySubject` was appending subjects instead of setting the passed value.
Additionally, it was not resetting the other filter subject field. That could cause errors, as server denies consumer API calls with both FilterSubject` and `FilterSubjects` set.`
Signed-off-by: Tomasz Pietrek <tomasz@nats.io>
=> Fix consumer subject filters

api/cluster.go, schema_source/jetstream/api/v1/definitions.json, schemas/jetstream/advisory/v1/consumer_leader_elected.json, schemas/jetstream/advisory/v1/consumer_quorum_lost.json, schemas/jetstream/advisory/v1/stream_leader_elected.json, schemas/jetstream/advisory/v1/stream_quorum_lost.json, schemas/jetstream/api/v1/consumer_create_response.json, schemas/jetstream/api/v1/consumer_info_response.json, schemas/jetstream/api/v1/consumer_list_response.json, schemas/jetstream/api/v1/stream_create_response.json, schemas/jetstream/api/v1/stream_info_response.json, schemas/jetstream/api/v1/stream_list_response.json, schemas/jetstream/api/v1/stream_update_response.json
This is to support nats-io/nats-server#4582.
=> Add `observer` to peer info

snapshots.go
Support creating and restoring snapshots from `io.Reader` and `io.Writer` instead of a file on disk.
=> Resolves #538: add support for writing and restoring snapshots to a buffer in memory instead of requiring a file on disk

consumers.go, test/consumers_test.go
Add DeliverBodies, which allows a consumer to be updated with headersOnly: false
This change will also be helpful for Nack: https://github.com/nats-io/nack/blob/main/controllers/jetstream/consumer.go#L408-L410
=> [ADD] DeliverBodies to disable headersOnly

consumer_query.go
Currently scoped to one stream only as we do not have the APIs to do bulk consumer querying and walking all streams is quite slow but callers could of course do the walking if they wish
=> Adds a consumer finder

monitor/stream.go, monitor/stream_test.go
Here we fix the cluster check to make sure that we don't run it if no ClusterExpectedPeers have been defined.
We also clean up the Mirror check to not run when sources have been defined, since the two are mutually exclusive.
=> (#1129) - Fix cluster and mirror checks

msginfo.go
Fixes: Incorrect received timestamp on 32-bit CPU #567
Signed-off-by: Arturs Laizans <arturs.laizans.ext@kiongroup.com>
=> Fix timestamp processing when int size 32

natscontext/context.go, natscontext/context_test.go, natscontext/testdata/gotest.json
Here we add the ability to use tilde in filepaths when defining contexts. Tilde will be expanded into the current user's home directory.
=> (#577) Add tilde expansion to context parsing

go.mod, go.sum, natscontext/context.go, natscontext/context_test.go, natscontext/expansion_test.go
Here we move tilde expansion to be as late as possible.
This prevents cli actions like `nats context edit` from rewriting the value of the path to file, and instead only expanding the tilde when needed.
=> (#577) Tilde expand context paths

consumers.go
This reverts 94286c087cbef2c36c8abdd3eb6e0d537d02f777 which introduced an under the covers change of user intent from single entry multi filters into a single filter, this was done to force the filter subject based consumer create to be used.
Problem is no other client does this so whatever backward compatible hopes there is or security gains just isn't realised and its just an unintended foot gun now
=> Revert 94286c087cbef2c36c8abdd3eb6e0d537d02f777

balancer/balancer.go, balancer/balancer_test.go, consumers.go, go.mod, go.sum, streams.go
Here we add the `balancer` package that allows us to balance stream and consumer leaders over a set of servers.
The balancer will determine what an even distribution of stream/consumer leaders are over the set of available servers are, and then trigger leader elections to rebalance the distribution.
A perfect distribution is not guaranteed after a run.
=> Add consumer and stream balancer

snapshots.go
https://github.com/nats-io/jsm.go/pull/545 introduced checking if during a stream snapshot there was some sort of error.
However `Nats-Request-Info` was checked which doesn't seem to contain this info.
The server reports the header `NATS/1.0 408 No Interest` which is reflected in the headers as:
`{Status: "408", Description: "No Interest"}`.
Source for reference: https://github.com/nats-io/nats-server/blob/a07bde9fa7d499c7039f74cac9d11f4c046b9250/server/jetstream_api.go#L3826
This PR fixes using the correct header, and also only calling `cancel()` after we've added the error to the `errc` as otherwise the error would not be logged.
=> Fix stream snapshot error messaging

audit/account_checks.go, audit/checks.go, audit/cluster_checks.go, audit/configuration.go, audit/leafnode_checks.go, audit/metacluster_checks.go, audit/server_checks.go, audit/stream_checks.go
This to improve using audit checks in multi threaded applications where each instance of the collection can have different sets of checks loaded
=> Create a collection of checks rather than global

audit/archive/writer.go, audit/gather/gather.go
Previously the responses would be ran through data types and then saved again for no good reason, this had the side effect of losing data for a gather process using older structs than the server generating the data
Now we store the data as received only indenting it for readability
=> Store raw server responses when gathering

schema_source/jetstream/api/v1/definitions.json
Similar to https://github.com/nats-io/nats.js/issues/186
It was added in https://github.com/nats-io/nats-server/commit/89ff13a5be680fda3fae2f2b53a12776928b82ed#diff-172561e6cce90cfe99be04c3a0381c1c019b97b809a429d87e60934e96f06139R823
And I did confirm that the number is compared to delivery count:
https://github.com/nats-io/nats-server/blob/5137ad891865be498a8f2ef42426033bd09c82d7/server/consumer.go#L4009
=> Update definitions.json redelivered-> delivered

api/consumers.go, schema_source/jetstream/api/v1/definitions.json, schemas/jetstream/api/v1/consumer_configuration.json, schemas/jetstream/api/v1/consumer_create_request.json, schemas/jetstream/api/v1/consumer_create_response.json, schemas/jetstream/api/v1/consumer_info_response.json, schemas/jetstream/api/v1/consumer_list_response.json
Here we add the yaml markup to ConsumerConfig, as well as update some missing values for conumer config in the API definition.
We also add missing UmarshallYAML and MarshalYAML functions to the enum fields used by ConsumerConfig so that they can render correctly when editing.
=> (#1145) Fix consumer interactive edit

monitor/consumer.go, monitor/js_account.go, monitor/js_account_test.go, monitor/stream.go, monitor/stream_msg.go, monitor/stream_msg_test.go
This enables domains, trace etc to be used
=> Expect jsm options on JS related monitors

README.md, consumer_query.go, jsm.go, match.go, match_noexpr.go, stream_query.go
This module uses `github.com/expr-lang/expr` which, because of the extensive use of the `reflect` package, disables go's compiler dead code elimination which can lead to bigger binaries.
This commit adds a `noexprlang` build tag that allows jsm.go users that do not use expression matching to entirely disable the use of the expr module so that they can benefit from go's dead code elimination if they are eligible to outside jsm.go.
References:
- https://golab.io/talks/getting-the-most-out-of-dead-code-elimination
- https://github.com/aarzilli/whydeadcode
- https://github.com/spf13/cobra/pull/1956
=> Add a noexprlang build tag

schema_source/jetstream/api/v1/definitions.json, schemas/jetstream/api/v1/consumer_create_response.json
`ConsumerInfo` has `pause_remaining` rather than `paused_until`.
https://github.com/nats-io/nats-server/blob/d0ce4c4ad29d3a363f7865c1e5cf12d345f55297/server/consumer.go#L66
Signed-off-by: Piotr Piotrowski [piotr@synadia.com](mailto:piotr@synadia.com)
=> Fixed invalid consumer info schema

audit/gather/gather.go
If we write `responseBytes` into the archive then we get the full raw JSON of the message rather than the raw profile bytes.
=> Fix gathering profiles in `audit` package

audit/account_checks.go, audit/account_checks_test.go, audit/archive/README.md, audit/archive/archive_test.go, audit/archive/paged_archive_test.go, audit/archive/paged_writer.go, audit/archive/reader.go, audit/archive/tag.go, audit/archive/writer.go, audit/cluster_checks.go, audit/gather/gather.go, audit/jetstream_checks.go, audit/leafnode_checks.go, audit/metacluster_checks.go, audit/server_checks.go
This changes how artifacts are stored in the archive, switching from a single artifact.json file to paged JSON files like .../artifact/0001.json. Profile data and special files (e.g., logs) still use the original single-file format, as paging doesn't apply.
Paged API requests have been implemented for the CONNZ, SUBSZ, and JSZ server endpoints. More endpoints can be supported as they gain pagination support.
Audit checks have been updated to iterate over paged data using the new Reader methods.
=> Update archiver to support paged artifact storage

stream_pager.go
Without this, when there is no filter set, the request will only ask for a given seq due to the omitempty
So any gap in the messages will terminate the viewer.
=> Ensure next_for subject is always set

monitor/connection.go, monitor/consumer.go, monitor/credentials.go, monitor/js_account.go, monitor/kv.go, monitor/meta.go, monitor/request.go, monitor/result.go, monitor/server.go, monitor/stream.go, monitor/stream_msg.go
It naively checks anything with a printf style arguments and complains when passed only one argument, even if no alternative exist.
It also only support turning the check off for the entire codebase not just some lines, so we just have to play along
=> Align with the needs of go 1.24 go vet

api/streams.go
With strict loading of JSON these would fail to load on 2.11 even if not in use
=> Make 2.12 new fields omit empty

api/consumers.go, api/streams.go, schema_source/jetstream/api/v1/consumer_list_response.json, schema_source/jetstream/api/v1/stream_list_response.json, schemas/jetstream/api/v1/consumer_list_response.json, schemas/jetstream/api/v1/stream_list_response.json
Offline assets will appear in the existing "missing" list for older tools and newer tools can access reasons in the new offline fields.
Stream info will error.
Supports https://github.com/nats-io/nats-server/pull/7158
=> Support offline assets

api/consumers.go, api/jetstream.go, api/jetstream_test.go, api/streams.go, consumers.go, manager.go, test/api_level_test.go
This is a POC that marks up structures with api_level="2" tags and tooling to automatically check all requests recursively and determine the highest required api level.
This is then used in setting the Nats-Required-Api-Level automatically for any caller
=> Auto setting of js api level header
