nats-io/jsm.go

- README.md
- consumers.go
- consumers_test.go
- jsm.go
- jsm_test.go
- request_options.go
- streams.go
- streams_test.go
- templates.go
> rework connection handling so multiple servers can be supported

- consumers.go
- go.mod
- go.sum
> ensures that NextMsgs do not error on ctx if messages were received

- consumers.go
- consumers_test.go
> ensure delivery policy is consistent

- consumers.go
> export the simple NextMsg

- consumers.go
> msg count is unused now

- api/consumers.go
- consumers.go
- consumers_test.go
- go.mod
- go.sum
> support new delivery policy based consumers

- go.mod
- go.sum
> latest nats dependency

- consumers.go
> fix npe when accessing time

- go.mod
- go.sum
> latest jetstream dependency

- .travis.yml
- api/example_event_schema_test.go
- api/example_parse_event_test.go
- api/example_validate_event_test.go
- api/schemas.go
> add examples for using events and schemas

- api/gen.go
- api/schemas_generated.go
- api/server/advisory/misc.go
- api/server/metric/service_latency.go
> use correct package for srv latency samples

- api/jetstream/advisory/api_audit.go
- api/jetstream/advisory/max_deliver.json.go
- api/jetstream/metric/consumer_ack.go
- api/server/advisory/client_connect.go
- api/server/advisory/client_disconnect.go
- api/server/metric/service_latency.go
> present event time stamps as time.Time

- api/server/metric/service_latency.go
> fix service latency timestamp type

- api/event/event.go
- api/jetstream/advisory/api_audit.go
- api/jetstream/advisory/max_deliver.json.go
- api/jetstream/metric/consumer_ack.go
- api/schemas.go
- api/schemas_test.go
- api/server/advisory/client_connect.go
- api/server/advisory/client_disconnect.go
- api/server/metric/service_latency.go
> support converting events into cloud events

- api/example_validate_event_test.go
- api/jetstream.go
- api/schemas_test.go
- api/streams.go
- streams.go
- streams_test.go
> support discard policy on streams

- consumers.go
> add a helper to report a consumer state snapshot

- api/streams.go
- go.mod
- go.sum
- streams.go
> use a JSON request for delete message

- api/consumers.go
- api/jetstream.go
- api/stream_templates.go
- api/streams.go
- consumers.go
- consumers_test.go
- go.mod
- go.sum
- jsm.go
- jsm_test.go
- streams.go
- streams_test.go
- templates.go
> use new format api subjects

- go.mod
- go.sum
> use latest jetstream branch

- api/consumers.go
- api/gen.go
- api/schemas_generated.go
- api/stream_templates.go
- api/streams.go
- go.mod
- go.sum
> generate all the validation and type helpers

- api/stream_templates.go
- api/streams.go
- jsm.go
- request_options.go
- streams.go
> support consumer paging, consistency updates

- snapshots.go
> also track the uncompressed size

- snapshots.go
> fix chunk size calculation

- snapshots.go
> support tracking sending bps

- snapshots.go
- snapshots_test.go
> add debug logs for restore

- snapshots.go
> optimise locking

- backup.go
> support backing up all data during config backup

- backup.go
> only backup file backed streams

- api/event/event.go
- api/jetstream/advisory/api_audit.go
- api/jetstream/advisory/consumer_action.go
- api/jetstream/advisory/max_deliver.go
- api/jetstream/advisory/restore_complete.go
- api/jetstream/advisory/restore_create.go
- api/jetstream/advisory/snapshot_complete.go
- api/jetstream/advisory/snapshot_create.go
- api/jetstream/advisory/stream_action.go
- api/jetstream/metric/consumer_ack.go
- api/schemas.go
- api/server/advisory/client_connect.go
- api/server/advisory/client_disconnect.go
- api/server/metric/service_latency.go
- go.mod
- go.sum
> add the ability to render events to text

- api/schemas.go
> support rendering JSON

- api/event/event.go
- api/jetstream/advisory/stream_action.go
- api/schemas.go
> correctly format ActionAdvisoryTypeV1

- api/event/event.go
- api/jetstream/advisory/snapshot_create.go
> produce human friendly numbers in advisories

- api/jetstream/advisory/snapshot_create.go
- msginfo.go
> fix data types for events and message metadata

- streams.go
- streams_test.go
> support fetching last known state to help speed up nats cli

- go.mod
- go.sum
- jsm.go
- streams.go
> add additional stream state caching

- jsm.go
> avoid infinite loop on iterableRequest

- consumers.go
> (#100) fix double error check

- consumers.go
- jsm.go
- jsm_test.go
- streams.go
- templates.go
> (#102) validate stream and consumer names before use

- api/jetstream.go
> correctly detect the last page of iterated results

- consumers.go
> deprecate the ill conceived subscribe helpers

- go.mod
- go.sum
> update nats server dependency

- api/server/metric/service_latency.go
> fix rendering service latencies when client detail is not opted in

- api/jetstream/advisory/api_audit.go
- api/jetstream/advisory/restore_complete.go
- api/jetstream/advisory/restore_create.go
- api/jetstream/advisory/snapshot_complete.go
- api/jetstream/advisory/snapshot_create.go
- api/server/advisory/client_connect.go
- api/server/advisory/client_disconnect.go
> consistency and formatting updates

- api/consumers.go
- go.mod
- go.sum
- snapshots.go
> restore chunk sizes are fixed

- api/consumers.go
> restore ack variables

- jsm.go
Signed-off-by: Masudur Rahman <masud@appscode.com>
> Fix NoValidate function

- api/schemas.go
- api/schemas_test.go
> support searching known schemas using regular expressions

- consumers.go
> add comments to consumer creation options

- stream_pager.go
- stream_pager_test.go
- streams.go
> add the ability to page through stream contens

- README.md
- stream_pager.go
> minor fixes

- api/streams.go
> ensure purge is always present

- api/consumers.go
- consumers.go
- consumers_test.go
- go.mod
- go.sum
> support consumer outstanding messages

- api/jetstream/advisory/api_audit.go
> fix rendering client details in events

- consumers.go
- consumers_test.go
- go.mod
- go.sum
> support the full next msg request format

- .github/workflows/go.yaml
- snapshots.go
> add go vet checks

- api/streams.go
> add the lookup suject

- go.mod
- go.sum
- manager.go
- manager_test.go
> add mgr.StreamLookup

- msginfo.go
- msginfo_test.go
> improve types used in msginfo

- manager.go
- manager_test.go
- streams_test.go
> allow stream names to be filtered

- msginfo.go
> support parsing a reply subject

- api/server/advisory/client_disconnect.go
- go.mod
- go.sum
> Release 0.0.20

- api/jetstream/advisory/max_deliver.go
- api/jetstream/advisory/terminated.go
- api/jetstream/metric/consumer_ack.go
> fix event rendering of sequences

- api/cluster.go
- api/consumers.go
- api/streams.go
> add cluster info to streams and consumers

- go.mod
- go.sum
- snapshots_test.go
> update server dependencies

- api/server/metric/service_latency.go
> further ClientInfo fixes

- manager.go
> trace on API errors

- api/jetstream/advisory/api_audit.go
- api/jetstream/advisory/restore_complete.go
- api/jetstream/advisory/restore_create.go
- api/jetstream/advisory/snapshot_complete.go
- api/jetstream/advisory/snapshot_create.go
> remove port from client info

- api/jetstream/advisory/consumer_leader_elected.go
- api/jetstream/advisory/cosumer_quorum_lost.go
- api/jetstream/advisory/stream_leader_elected.go
- api/jetstream/advisory/stream_quorum_lost.go
> clarify short event formats for quorum events

- api/jetstream/advisory/consumer_leader_elected.go
- api/jetstream/advisory/cosumer_quorum_lost.go
- api/jetstream/advisory/stream_leader_elected.go
- api/jetstream/advisory/stream_quorum_lost.go
> consistency update for short raft advisories

- snapshots.go
> updates to improve progress reporting

- stream_pager.go
> ensure messages are acked in stream pager

- consumers.go
- jsm.go
- manager.go
- natscontext/context.go
- options.go
> initial support for confgurable subject prefixes

- consumers.go
> handle more prefixed subjects

- consumers.go
- manager.go
> improve tracing and handling of prefixes

- api/cluster.go
- jsm.go
- manager.go
> support meta peer removal

- snapshots.go
- snapshots_test.go
> support change configuration and stream names when restoring

- consumers.go
> ensure UTC times are sent to the server api

- stream_pager.go
> support filter subjects for stream view

- consumers.go
> cache consumer info and add LastInfo()

- consumers.go
> consistency update

- api/gen.go
- api/schemas_generated.go
- api/streams.go
- schema_source/jetstream/api/v1/definitions.json
- schema_source/jetstream/api/v1/stream_info_request.json
- schemas/jetstream/api/v1/stream_create_response.json
- schemas/jetstream/api/v1/stream_info_request.json
- schemas/jetstream/api/v1/stream_info_response.json
- schemas/jetstream/api/v1/stream_list_response.json
- schemas/jetstream/api/v1/stream_restore_request.json
- schemas/jetstream/api/v1/stream_snapshot_response.json
- schemas/jetstream/api/v1/stream_update_response.json
> support opt-in to the deleted detail in stream info

- schema_source/jetstream/api/v1/definitions.json
- schemas/jetstream/api/v1/stream_create_response.json
- schemas/jetstream/api/v1/stream_info_response.json
- schemas/jetstream/api/v1/stream_list_response.json
- schemas/jetstream/api/v1/stream_restore_request.json
- schemas/jetstream/api/v1/stream_snapshot_response.json
- schemas/jetstream/api/v1/stream_update_response.json
> allow null lost messages items

- schema_source/jetstream/api/v1/definitions.json
> lost msgs fix

- schemas/jetstream/api/v1/stream_create_response.json
- schemas/jetstream/api/v1/stream_info_response.json
- schemas/jetstream/api/v1/stream_list_response.json
- schemas/jetstream/api/v1/stream_restore_request.json
- schemas/jetstream/api/v1/stream_snapshot_response.json
- schemas/jetstream/api/v1/stream_update_response.json
> compile schemas

- natscontext/context.go
> support js domain in contexts

- jsm.go
- jsm_test.go
- natscontext/context.go
> correctly calculate domain subjects

- api/consumers.go
- consumers.go
- consumers_test.go
- schema_source/jetstream/api/v1/definitions.json
- schemas/jetstream/api/v1/consumer_configuration.json
- schemas/jetstream/api/v1/consumer_create_request.json
- schemas/jetstream/api/v1/consumer_create_response.json
- schemas/jetstream/api/v1/consumer_info_response.json
- schemas/jetstream/api/v1/consumer_list_response.json
> support MaxWaiting

- consumers.go
> getter for max waiting

- natscontext/context.go
> support token authentication

- api/streams.go
- go.mod
- go.sum
- schema_source/jetstream/api/v1/definitions.json
- schemas/jetstream/api/v1/stream_configuration.json
- schemas/jetstream/api/v1/stream_create_request.json
- schemas/jetstream/api/v1/stream_create_response.json
- schemas/jetstream/api/v1/stream_info_response.json
- schemas/jetstream/api/v1/stream_list_response.json
- schemas/jetstream/api/v1/stream_restore_request.json
- schemas/jetstream/api/v1/stream_snapshot_response.json
- schemas/jetstream/api/v1/stream_template_configuration.json
- schemas/jetstream/api/v1/stream_template_create_request.json
- schemas/jetstream/api/v1/stream_template_create_response.json
- schemas/jetstream/api/v1/stream_template_info_response.json
- schemas/jetstream/api/v1/stream_update_request.json
- schemas/jetstream/api/v1/stream_update_response.json
- streams.go
- streams_test.go
> support per subject msgs retention

- backoff/backoff.go
- governor/governor.go
- governor/governor_test.go
> support backoffs and add some configurables to governor

- governor/governor.go
> usability updates

- api/consumers.go
- api/schemas_generated.go
- consumers.go
- events.go
- kv/README.md
- kv/jetstream_backend.go
- kv/jetstream_backend_test.go
- kv/jetstream_result.go
- kv/jetstream_status.go
- kv/jetstream_watch.go
- kv/kv.go
- kv/kv_test.go
- kv/opts.go
- kv/read_cache.go
- kv/read_cache_test.go
- kv/stdout_logger.go
- manager.go
- msginfo.go
- schema_source/jetstream/api/v1/definitions.json
- schemas/jetstream/api/v1/consumer_configuration.json
- schemas/jetstream/api/v1/consumer_create_request.json
- schemas/jetstream/api/v1/consumer_create_response.json
- schemas/jetstream/api/v1/consumer_info_response.json
- schemas/jetstream/api/v1/consumer_list_response.json
- schemas/server/errors.json
- streams.go
- streams_test.go
> Initial CLI focussed KV implementation

- kv/jetstream_backend.go
- kv/jetstream_backend_test.go
- kv/jetstream_status.go
- kv/kv.go
- kv/opts.go
> minor tweaks to status etc

- kv/jetstream_watch.go
> fix watch consumer manager

- governor/governor.go
> do not configure duplicate tracking for governors

- kv/README.md
- kv/jetstream_backend.go
- kv/jetstream_backend_test.go
> move kv to $KV subjects

- kv/jetstream_backend.go
- kv/jetstream_backend_test.go
> avoid default 1 year ttl on kv buckets

- kv/jetstream_backend.go
- kv/jetstream_backend_test.go
> dupe window cannot be disabled, set to same as ttl if needed

- kv/README.md
- kv/jetstream_backend.go
- kv/jetstream_backend_test.go
- kv/jetstream_result.go
- kv/kv.go
- kv/read_cache.go
- kv/read_cache_test.go
> support non destructive deletes

- kv/jetstream_backend.go
- kv/jetstream_status.go
- kv/kv.go
> expose TTL

- kv/jetstream_backend.go
> fix accessing loaded stream

- kv/jetstream_backend.go
- kv/opts.go
> add additional kv bucket size controls

- kv/jetstream_status.go
- kv/kv.go
> expose stream size limits on status

- kv/jetstream_backend.go
- kv/jetstream_backend_test.go
- kv/jetstream_result.go
- kv/jetstream_watch.go
- kv/kv.go
- kv/opts.go
- kv/read_cache.go
- kv/read_cache_test.go
> bytes based kv api

- governor/governor.go
- governor/governor_test.go
> allow subjects to be customised

- governor/governor.go
> add some utilities to the manager

- governor/governor.go
- governor/governor_test.go
- kv/jetstream_watch.go
- kv/stdout_logger.go
> fix logger method name confusion

- api/schemas_generated.go
- governor/governor.go
- jsm.go
- jsm_test.go
- schemas/server/errors.json
> do not log nats error code 10077

- schema_source/jetstream/api/v1/definitions.json
- schemas/jetstream/api/v1/account_info_response.json
- schemas/jetstream/api/v1/consumer_create_response.json
- schemas/jetstream/api/v1/consumer_delete_response.json
- schemas/jetstream/api/v1/consumer_info_response.json
- schemas/jetstream/api/v1/consumer_leader_stepdown_response.json
- schemas/jetstream/api/v1/consumer_list_response.json
- schemas/jetstream/api/v1/consumer_names_response.json
- schemas/jetstream/api/v1/meta_leader_stepdown_response.json
- schemas/jetstream/api/v1/meta_server_remove_response.json
- schemas/jetstream/api/v1/pub_ack_response.json
- schemas/jetstream/api/v1/stream_create_response.json
- schemas/jetstream/api/v1/stream_delete_response.json
- schemas/jetstream/api/v1/stream_info_response.json
- schemas/jetstream/api/v1/stream_leader_stepdown_response.json
- schemas/jetstream/api/v1/stream_list_response.json
- schemas/jetstream/api/v1/stream_msg_delete_response.json
- schemas/jetstream/api/v1/stream_msg_get_response.json
- schemas/jetstream/api/v1/stream_names_response.json
- schemas/jetstream/api/v1/stream_purge_response.json
- schemas/jetstream/api/v1/stream_remove_peer_response.json
- schemas/jetstream/api/v1/stream_restore_response.json
- schemas/jetstream/api/v1/stream_snapshot_response.json
- schemas/jetstream/api/v1/stream_template_create_response.json
- schemas/jetstream/api/v1/stream_template_delete_response.json
- schemas/jetstream/api/v1/stream_template_info_response.json
- schemas/jetstream/api/v1/stream_template_names_response.json
- schemas/jetstream/api/v1/stream_update_response.json
> add schema entry for err code

- governor/governor.go
- governor/governor_test.go
> report last time an entry entered a governor

- api/schemas_generated.go
- governor/governor.go
- governor/governor_test.go
- schemas/server/errors.json
> make the sequence available to callers, finish once only

- governor/governor.go
- governor/governor_test.go
> report the evicted name

- api/server/advisory/client_connect.go
- api/server/advisory/client_disconnect.go
- api/server/advisory/misc.go
- schema_source/definitions.json
- schemas/jetstream/advisory/v1/api_audit.json
- schemas/jetstream/advisory/v1/restore_complete.json
- schemas/jetstream/advisory/v1/restore_create.json
- schemas/jetstream/advisory/v1/snapshot_complete.json
- schemas/jetstream/advisory/v1/snapshot_create.json
- schemas/server/advisory/v1/client_connect.json
- schemas/server/advisory/v1/client_disconnect.json
- schemas/server/metric/v1/service_latency.json
Signed-off-by: Matthias Hanel <mh@synadia.com>
> [added] kind and client type to client info

- governor/governor.go
- kv/jetstream_backend.go
- kv/jetstream_backend_test.go
- kv/jetstream_entry.go
- kv/jetstream_status.go
- kv/jetstream_watch.go
- kv/kv.go
- kv/read_cache.go
- kv/read_cache_test.go
> updates for the latest adr changes

- election/election.go
- election/options.go
> support campaign backoffs in elections

- schema_source/jetstream/api/v1/definitions.json
- schemas/jetstream/api/v1/consumer_configuration.json
- schemas/jetstream/api/v1/consumer_create_request.json
- schemas/jetstream/api/v1/consumer_create_response.json
- schemas/jetstream/api/v1/consumer_info_response.json
- schemas/jetstream/api/v1/consumer_list_response.json
- schemas/jetstream/api/v1/stream_configuration.json
- schemas/jetstream/api/v1/stream_create_request.json
- schemas/jetstream/api/v1/stream_create_response.json
- schemas/jetstream/api/v1/stream_info_response.json
- schemas/jetstream/api/v1/stream_list_response.json
- schemas/jetstream/api/v1/stream_restore_request.json
- schemas/jetstream/api/v1/stream_snapshot_response.json
- schemas/jetstream/api/v1/stream_template_configuration.json
- schemas/jetstream/api/v1/stream_template_create_request.json
- schemas/jetstream/api/v1/stream_template_create_response.json
- schemas/jetstream/api/v1/stream_template_info_response.json
- schemas/jetstream/api/v1/stream_update_request.json
- schemas/jetstream/api/v1/stream_update_response.json
> add consumer and stream descriptions

- api/consumers.go
- api/schemas_generated.go
- api/streams.go
- consumers.go
- consumers_test.go
- go.mod
- go.sum
- schemas/server/errors.json
- streams.go
- streams_test.go
> support descriptions for consumers and streams

- kv/jetstream_backend.go
- kv/jetstream_backend_test.go
> avoid doing key operations on wildcards

- schema_source/jetstream/api/v1/definitions.json
- schemas/jetstream/api/v1/stream_configuration.json
- schemas/jetstream/api/v1/stream_create_request.json
- schemas/jetstream/api/v1/stream_create_response.json
- schemas/jetstream/api/v1/stream_info_response.json
- schemas/jetstream/api/v1/stream_list_response.json
- schemas/jetstream/api/v1/stream_restore_request.json
- schemas/jetstream/api/v1/stream_snapshot_response.json
- schemas/jetstream/api/v1/stream_template_configuration.json
- schemas/jetstream/api/v1/stream_template_create_request.json
- schemas/jetstream/api/v1/stream_template_create_response.json
- schemas/jetstream/api/v1/stream_template_info_response.json
- schemas/jetstream/api/v1/stream_update_request.json
- schemas/jetstream/api/v1/stream_update_response.json
> fix some uint confusion

- go.mod
- go.sum
- governor/governor.go
- kv/jetstream_backend.go
- stream_pager.go
> set some descriptions on streams and consumers

- api/streams.go
- schema_source/jetstream/api/v1/pub_ack_response.json
- schemas/jetstream/api/v1/pub_ack_response.json
> support domains in pub ack

- schema_source/jetstream/api/v1/definitions.json
- schemas/jetstream/api/v1/consumer_configuration.json
- schemas/jetstream/api/v1/consumer_create_request.json
- schemas/jetstream/api/v1/consumer_create_response.json
- schemas/jetstream/api/v1/consumer_info_response.json
- schemas/jetstream/api/v1/consumer_list_response.json
- schemas/jetstream/api/v1/stream_configuration.json
- schemas/jetstream/api/v1/stream_create_request.json
- schemas/jetstream/api/v1/stream_create_response.json
- schemas/jetstream/api/v1/stream_info_response.json
- schemas/jetstream/api/v1/stream_list_response.json
- schemas/jetstream/api/v1/stream_restore_request.json
- schemas/jetstream/api/v1/stream_snapshot_response.json
- schemas/jetstream/api/v1/stream_template_configuration.json
- schemas/jetstream/api/v1/stream_template_create_request.json
- schemas/jetstream/api/v1/stream_template_create_response.json
- schemas/jetstream/api/v1/stream_template_info_response.json
- schemas/jetstream/api/v1/stream_update_request.json
- schemas/jetstream/api/v1/stream_update_response.json
> add some hints about time.Time fields

- msginfo.go
- msginfo_test.go
> support new style ack subjects

- schema_source/jetstream/api/v1/definitions.json
- schemas/jetstream/api/v1/consumer_configuration.json
- schemas/jetstream/api/v1/consumer_create_request.json
- schemas/jetstream/api/v1/consumer_create_response.json
- schemas/jetstream/api/v1/consumer_info_response.json
- schemas/jetstream/api/v1/consumer_list_response.json
> add defaults to consumer structures

- api/jetstream.go
- api/schemas_generated.go
- api/streams.go
- go.mod
- go.sum
- schema_source/jetstream/api/v1/definitions.json
- schemas/server/errors.json
- streams.go
- streams_test.go
> support sealed streams

- api/schemas_generated.go
- schemas/jetstream/api/v1/stream_configuration.json
- schemas/jetstream/api/v1/stream_create_request.json
- schemas/jetstream/api/v1/stream_create_response.json
- schemas/jetstream/api/v1/stream_info_response.json
- schemas/jetstream/api/v1/stream_list_response.json
- schemas/jetstream/api/v1/stream_restore_request.json
- schemas/jetstream/api/v1/stream_snapshot_response.json
- schemas/jetstream/api/v1/stream_template_configuration.json
- schemas/jetstream/api/v1/stream_template_create_request.json
- schemas/jetstream/api/v1/stream_template_create_response.json
- schemas/jetstream/api/v1/stream_template_info_response.json
- schemas/jetstream/api/v1/stream_update_request.json
- schemas/jetstream/api/v1/stream_update_response.json
> update schemas for sealed streams

- api/jetstream.go
- go.mod
- go.sum
- kv/jetstream_backend.go
- kv/jetstream_backend_test.go
- kv/kv.go
- kv/read_cache.go
- kv/read_cache_test.go
> kv purge(key) using rollups, some updates for ADR

- api/consumers.go
- api/schemas_generated.go
- api/streams.go
- consumers.go
- consumers_test.go
- go.mod
- go.sum
- kv/jetstream_backend.go
- schema_source/jetstream/api/v1/definitions.json
- schemas/jetstream/api/v1/consumer_configuration.json
- schemas/jetstream/api/v1/consumer_create_request.json
- schemas/jetstream/api/v1/consumer_create_response.json
- schemas/jetstream/api/v1/consumer_info_response.json
- schemas/jetstream/api/v1/consumer_list_response.json
- schemas/jetstream/api/v1/stream_configuration.json
- schemas/jetstream/api/v1/stream_create_request.json
- schemas/jetstream/api/v1/stream_create_response.json
- schemas/jetstream/api/v1/stream_info_response.json
- schemas/jetstream/api/v1/stream_list_response.json
- schemas/jetstream/api/v1/stream_restore_request.json
- schemas/jetstream/api/v1/stream_snapshot_response.json
- schemas/jetstream/api/v1/stream_template_configuration.json
- schemas/jetstream/api/v1/stream_template_create_request.json
- schemas/jetstream/api/v1/stream_template_create_response.json
- schemas/jetstream/api/v1/stream_template_info_response.json
- schemas/jetstream/api/v1/stream_update_request.json
- schemas/jetstream/api/v1/stream_update_response.json
- schemas/server/errors.json
- streams.go
- streams_test.go
> additional stream permissions and headers only consumers

- go.mod
- go.sum
- jsm.go
- streams.go
> additional helpers to detect internal streams

- consumers.go
- consumers_test.go
- go.mod
- go.sum
- streams.go
> support udpating consumers

- manager_test.go
- stream_query.go
- stream_query_test.go
> add a basic facility to query streams

- manager_test.go
- stream_query.go
- stream_query_test.go
This avoids awkward boolean pointers etc
> use a functional query api

- consumers.go
- consumers_test.go
- go.mod
- go.sum
> tweak linear backoff to start nearer to min

- consumers.go
- jsm.go
> extract the backoff logic into a standalone

- consumers.go
> support a specifically supplied backoff policy

- snapshots.go
> improve restore error handling

- go.mod
- go.sum
- stream_pager.go
> Handle 408 header in stream pager

- natscontext/context.go
- natscontext/context_test.go
- natscontext/testdata/gotest.json
Signed-off-by: Matthew DeVenny <matt@boxboat.com>
Addresses #364
> Add natscontext.NewFromFile

- api/schemas_generated.go
- schema_source/jetstream/api/v1/definitions.json
- schemas/jetstream/api/v1/account_info_response.json
> additional JS 2.8 compat

- streams.go
- streams_test.go
> prevent paging WQ streams

- go.mod
- go.sum
- manager.go
- manager_test.go
- testdata/bytes_required.cfg
> helper to determine if streams require max bytes set

- .github/workflows/go.yaml
- go.mod
- go.sum
Also arrange tests against go 1.18
> prepare release 0.0.31

- go.mod
- go.sum
- manager.go
- stream_query.go
- stream_query_test.go
> support matching streams on subject in stream query

- api/consumers.go
- schema_source/jetstream/api/v1/consumer_getnext_request.json
- schema_source/jetstream/api/v1/definitions.json
- schemas/jetstream/api/v1/consumer_configuration.json
- schemas/jetstream/api/v1/consumer_create_request.json
- schemas/jetstream/api/v1/consumer_create_response.json
- schemas/jetstream/api/v1/consumer_getnext_request.json
- schemas/jetstream/api/v1/consumer_info_response.json
- schemas/jetstream/api/v1/consumer_list_response.json
> support consumer configuration limiting pull max bytes

- api/consumers.go
- consumers.go
> add config helps for MaxRequestMaxBytes

- api/consumers.go
- consumers.go
- consumers_test.go
- schema_source/jetstream/api/v1/definitions.json
- schemas/jetstream/api/v1/consumer_configuration.json
- schemas/jetstream/api/v1/consumer_create_request.json
- schemas/jetstream/api/v1/consumer_create_response.json
- schemas/jetstream/api/v1/consumer_info_response.json
- schemas/jetstream/api/v1/consumer_list_response.json
> support overriding R and memory storage for consumers

- api/streams.go
- streams.go
- streams_test.go
> support stream republish

- schema_source/jetstream/api/v1/definitions.json
- schemas/jetstream/api/v1/stream_configuration.json
- schemas/jetstream/api/v1/stream_create_request.json
- schemas/jetstream/api/v1/stream_create_response.json
- schemas/jetstream/api/v1/stream_info_response.json
- schemas/jetstream/api/v1/stream_list_response.json
- schemas/jetstream/api/v1/stream_restore_request.json
- schemas/jetstream/api/v1/stream_snapshot_response.json
- schemas/jetstream/api/v1/stream_template_configuration.json
- schemas/jetstream/api/v1/stream_template_create_request.json
- schemas/jetstream/api/v1/stream_template_create_response.json
- schemas/jetstream/api/v1/stream_template_info_response.json
- schemas/jetstream/api/v1/stream_update_request.json
- schemas/jetstream/api/v1/stream_update_response.json
> update schemas for stream repub

- api/schemas_generated.go
- schemas/server/errors.json
> update server errors

- schema_source/jetstream/api/v1/definitions.json
- schemas/jetstream/api/v1/stream_configuration.json
- schemas/jetstream/api/v1/stream_create_request.json
- schemas/jetstream/api/v1/stream_create_response.json
- schemas/jetstream/api/v1/stream_info_response.json
- schemas/jetstream/api/v1/stream_list_response.json
- schemas/jetstream/api/v1/stream_restore_request.json
- schemas/jetstream/api/v1/stream_snapshot_response.json
- schemas/jetstream/api/v1/stream_template_configuration.json
- schemas/jetstream/api/v1/stream_template_create_request.json
- schemas/jetstream/api/v1/stream_template_create_response.json
- schemas/jetstream/api/v1/stream_template_info_response.json
- schemas/jetstream/api/v1/stream_update_request.json
- schemas/jetstream/api/v1/stream_update_response.json
> fix object keys in requires for subject mappings

- schema_source/jetstream/api/v1/definitions.json
- schemas/jetstream/api/v1/stream_configuration.json
- schemas/jetstream/api/v1/stream_create_request.json
- schemas/jetstream/api/v1/stream_create_response.json
- schemas/jetstream/api/v1/stream_info_response.json
- schemas/jetstream/api/v1/stream_list_response.json
- schemas/jetstream/api/v1/stream_restore_request.json
- schemas/jetstream/api/v1/stream_snapshot_response.json
- schemas/jetstream/api/v1/stream_template_configuration.json
- schemas/jetstream/api/v1/stream_template_create_request.json
- schemas/jetstream/api/v1/stream_template_create_response.json
- schemas/jetstream/api/v1/stream_template_info_response.json
- schemas/jetstream/api/v1/stream_update_request.json
- schemas/jetstream/api/v1/stream_update_response.json
> rename dest key for subject mappings

- schema_source/jetstream/api/v1/definitions.json
- schemas/jetstream/api/v1/consumer_configuration.json
- schemas/jetstream/api/v1/consumer_create_request.json
- schemas/jetstream/api/v1/consumer_create_response.json
- schemas/jetstream/api/v1/consumer_info_response.json
- schemas/jetstream/api/v1/consumer_list_response.json
> minor schema spelling and json correctness

- natscontext/context.go
> support deleting the selected ctx if its the only one

- api/streams.go
- schema_source/jetstream/api/v1/definitions.json
- schemas/jetstream/api/v1/stream_configuration.json
- schemas/jetstream/api/v1/stream_create_request.json
- schemas/jetstream/api/v1/stream_create_response.json
- schemas/jetstream/api/v1/stream_info_response.json
- schemas/jetstream/api/v1/stream_list_response.json
- schemas/jetstream/api/v1/stream_restore_request.json
- schemas/jetstream/api/v1/stream_snapshot_response.json
- schemas/jetstream/api/v1/stream_template_configuration.json
- schemas/jetstream/api/v1/stream_template_create_request.json
- schemas/jetstream/api/v1/stream_template_create_response.json
- schemas/jetstream/api/v1/stream_template_info_response.json
- schemas/jetstream/api/v1/stream_update_request.json
- schemas/jetstream/api/v1/stream_update_response.json
- streams.go
> support permitting direct get on streams

- snapshots.go
- snapshots_test.go
> detect snapshots of memory streams and fail with a error constant

- api/cluster.go
- manager.go
> fix subject for stream move

- api/server/advisory/account_connections.go
- schema_source/server/advisory/v1/account_connections.json
> add support for account data stats

- api/cluster.go
- go.mod
- go.sum
> fix json keys for meta stream move

- governor/governor.go
This allows a governor to elect not delete his claim to
a slot when completed doing the work.
Enabling this on a governor with a max age of 1 hour will
have the outcome that a specific piece of work can only be
done n times per hour.
If you want to control a cronjob so it runs once only on
multiple machines you would create a governor with this option
set and the governor will stay at capacity long enough for
all other attempts to timeout
> Allow governors to not leave the governor on completion

- api/schemas_generated.go
- api/streams.go
- go.mod
- go.sum
- schema_source/jetstream/api/v1/stream_msg_get_request.json
- schemas/jetstream/api/v1/stream_msg_get_request.json
- schemas/server/advisory/v1/account_connections.json
> add NextFor to message request

- go.mod
- go.sum
- manager.go
- streams.go
- streams_test.go
> allow contained subjects to be retrieved for a stream

- streams.go
> move allow direct to opt-in

- api/cluster.go
- api/schemas_generated.go
- go.mod
- go.sum
- schema_source/jetstream/api/v1/meta_server_remove_request.json
- schemas/jetstream/api/v1/meta_server_remove_request.json
- schemas/server/errors.json
> Allow servers to be removed from meta cluster by id

- go.mod
- go.sum
- manager.go
> Allow MetaPeerRemove() to be supplied an id and name

- api/schemas_generated.go
- schema_source/jetstream/api/v1/stream_names_request.json
> update schemas to indicate stream names can be filtered

- api/streams.go
- backup.go
- manager.go
- manager_test.go
- schema_source/jetstream/api/v1/stream_list_request.json
- schema_source/jetstream/api/v1/stream_names_request.json
- schemas/jetstream/api/v1/stream_list_request.json
- stream_query.go
> support filter in stream list and related functions

- api/cluster.go
- api/gen.go
- api/schemas_generated.go
- go.mod
- go.sum
- manager.go
- schema_source/jetstream/api/v1/meta_account_purge_response.json
- schemas/jetstream/api/v1/meta_account_purge_response.json
- schemas/server/errors.json
> support purging all data from an account

- api/consumers.go
@ripienaar I discovered this new subject was missing when I was updating the docs to mention it (a user asked about it in Slack). This PR only includes the subject, but I did not change the implementation for the manager. Is that fine with you or would you prefer me update that as well?
> Add new create consumer API subject

- api/schemas.go
> adds a helper to parse and validate

- go.mod
- go.sum
> downgrade to an earlier dev branch

- api/streams.go
- schema_source/jetstream/api/v1/definitions.json
- schemas/jetstream/api/v1/stream_configuration.json
- schemas/jetstream/api/v1/stream_create_request.json
- schemas/jetstream/api/v1/stream_create_response.json
- schemas/jetstream/api/v1/stream_info_response.json
- schemas/jetstream/api/v1/stream_list_response.json
- schemas/jetstream/api/v1/stream_restore_request.json
- schemas/jetstream/api/v1/stream_snapshot_response.json
- schemas/jetstream/api/v1/stream_template_configuration.json
- schemas/jetstream/api/v1/stream_template_create_request.json
- schemas/jetstream/api/v1/stream_template_create_response.json
- schemas/jetstream/api/v1/stream_template_info_response.json
- schemas/jetstream/api/v1/stream_update_request.json
- schemas/jetstream/api/v1/stream_update_response.json
Adds stream subject transform support
> Add stream subject transform support

- api/streams.go
- schema_source/jetstream/api/v1/definitions.json
- schemas/jetstream/api/v1/stream_configuration.json
- schemas/jetstream/api/v1/stream_create_request.json
- schemas/jetstream/api/v1/stream_create_response.json
- schemas/jetstream/api/v1/stream_info_response.json
- schemas/jetstream/api/v1/stream_list_response.json
- schemas/jetstream/api/v1/stream_restore_request.json
- schemas/jetstream/api/v1/stream_snapshot_response.json
- schemas/jetstream/api/v1/stream_template_configuration.json
- schemas/jetstream/api/v1/stream_template_create_request.json
- schemas/jetstream/api/v1/stream_template_create_response.json
- schemas/jetstream/api/v1/stream_template_info_response.json
- schemas/jetstream/api/v1/stream_update_request.json
- schemas/jetstream/api/v1/stream_update_response.json
- streams.go
Prerequisite to updating the NATS CLI for configuring stream compression. ADR to follow for other clients.
> Add compression to stream config

- api/streams.go
- schema_source/jetstream/api/v1/definitions.json
- schemas/jetstream/api/v1/stream_configuration.json
- schemas/jetstream/api/v1/stream_create_request.json
- schemas/jetstream/api/v1/stream_create_response.json
- schemas/jetstream/api/v1/stream_info_response.json
- schemas/jetstream/api/v1/stream_list_response.json
- schemas/jetstream/api/v1/stream_restore_request.json
- schemas/jetstream/api/v1/stream_snapshot_response.json
- schemas/jetstream/api/v1/stream_template_configuration.json
- schemas/jetstream/api/v1/stream_template_create_request.json
- schemas/jetstream/api/v1/stream_template_create_response.json
- schemas/jetstream/api/v1/stream_template_info_response.json
- schemas/jetstream/api/v1/stream_update_request.json
- schemas/jetstream/api/v1/stream_update_response.json
Adds multi-subject filtering (and associated transforms) to stream sources (see https://github.com/nats-io/nats-server/pull/4276)
> [ADDED] multi-subject filtering (and associated transforms) to stream sources

- api/consumers.go
- go.mod
- go.sum
- schema_source/jetstream/api/v1/consumer_create_request.json
- schemas/jetstream/api/v1/consumer_create_request.json
See https://github.com/nats-io/nats-server/pull/4217
> [ADDED] action in create consumer requests

- streams.go
Signed-off-by: Jarema <melgaer@gmail.com>
> Add subject transform config option

- audit/archive/reader.go
- audit/archive/tag.go
- audit/checks.go
- audit/examples_collection.go
- audit/gather/gather.go
- audit/gather/logger.go
- audit/server_checks.go
Update server checks to use them
> Add some check helpers

- monitor/request.go
- monitor/request_test.go
For consistency with other checks
> Use seconds for durations in request test

- audit/archive/reader.go
Here we implement an inverted index to improve tag lookup when trying to load a file from the archive.
We also stop using reflect in the EachCluserServerX methods and use generics instead.
> Improve Reader memory usage and performance

- audit/account_checks.go
- audit/account_checks_test.go
- audit/archive/reader.go
- audit/cluster_checks_test.go
- audit/configuration.go
- audit/jetstream_checks.go
- audit/jetstream_checks_test.go
- audit/leafnode_checks_test.go
- audit/metacluster_checks_test.go
- audit/server_checks.go
- audit/server_checks_test.go
In the past units of type PercentageUnit were stored as numbers between 0 and 1. We now represent these values as numbers between 0 and 100.
This commit also adds tests for all the checks we have today.
> Update PercentageUnit calculations

- audit/jetstream_checks.go
- monitor/consumer.go
- monitor/consumer_test.go
- monitor/js_account.go
- monitor/stream.go
- monitor/stream_msg.go
Also consistency updates on consumer check
> Updates monitor connected checks to improve embedability

- go.mod
- go.sum
- manager.go
- streams.go
- test/streams_test.go
Server now does these and better, so we can remove this
> Remove client side check for overlapping subjects

- audit/gather/gather.go
One is for the full stacks, one is for the aggregated form that contains the goroutine tags. These are much easier formats to work with.
> Gather separated goroutine profiles

- api/streams.go
- schema_source/jetstream/api/v1/definitions.json
- schemas/jetstream/api/v1/stream_configuration.json
- schemas/jetstream/api/v1/stream_create_request.json
- schemas/jetstream/api/v1/stream_create_response.json
- schemas/jetstream/api/v1/stream_info_response.json
- schemas/jetstream/api/v1/stream_list_response.json
- schemas/jetstream/api/v1/stream_restore_request.json
- schemas/jetstream/api/v1/stream_snapshot_response.json
- schemas/jetstream/api/v1/stream_template_configuration.json
- schemas/jetstream/api/v1/stream_template_create_request.json
- schemas/jetstream/api/v1/stream_template_create_response.json
- schemas/jetstream/api/v1/stream_template_info_response.json
- schemas/jetstream/api/v1/stream_update_request.json
- schemas/jetstream/api/v1/stream_update_response.json
- streams.go
To facilitate testing of https://github.com/nats-io/nats-server/pull/6966 and https://github.com/nats-io/nats-architecture-and-design/pull/346
> Initial support for atomic batches
